# Generated by Django 5.1 on 2024-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
